// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Meetup = require("./interactions/Meetup.bs.js");

var configs = [Meetup.config];

function init(db) {
  var meetup = function (param, param$1) {
    return Meetup.make(db, param, param$1);
  };
  var allCommands = {
    hd: meetup,
    tl: /* [] */0
  };
  var exec = function (interaction, commands) {
    if (!commands) {
      return ;
    }
    var tail = commands.tl;
    var next = function (param) {
      exec(interaction, tail);
    };
    Curry._2(commands.hd, interaction, next);
  };
  return function (i) {
    exec(i, allCommands);
  };
}

exports.configs = configs;
exports.init = init;
/* Meetup Not a pure module */
