// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Aqi = require("./commands-rescript/Aqi.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var StdLib = require("./common/StdLib.bs.js");
var Christmas = require("./commands-rescript/Christmas.bs.js");

function toString(a) {
  return StdLib.A.join(Curry._1(StdLib.L.toArray, a), " ");
}

function run(message) {
  var request = StdLib.A.toList(message.content.split(" "));
  var command;
  var exit = 0;
  if (request) {
    switch (request.hd) {
      case "!aqi" :
          if (request.tl) {
            exit = 1;
          } else {
            command = Aqi.post;
          }
          break;
      case "!christmas" :
          if (request.tl) {
            exit = 1;
          } else {
            command = Christmas.daysLeft;
          }
          break;
      default:
        exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    command = (function (prim) {
        
      });
  }
  return Curry._1(command, message);
}

exports.toString = toString;
exports.run = run;
/* Aqi Not a pure module */
