// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pong = require("./commands-rescript/Pong.bs.js");
var Tldr = require("./commands-rescript/Tldr.bs.js");
var Version = require("./commands-rescript/Version.bs.js");

var commandList = [
  Pong.command,
  Tldr.command,
  Version.command
];

exports.commandList = commandList;
/* Pong Not a pure module */
