// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DifferenceInDays = require("date-fns/differenceInDays");

function festivize(msg) {
  return "🎄☃️☃️🎄🎁 " + msg + " 🎁🎄☃️☃️🎄";
}

function pluralize(word, count) {
  if (count !== 1) {
    return word + "S";
  } else {
    return word;
  }
}

function daysUntilChristmas(now) {
  var year = now.getFullYear();
  var month = now.getMonth();
  var date = now.getDate();
  var xmasYear = month !== 11 || date <= 25 ? year : year + 1;
  var christmas = new Date(xmasYear, 11, 25, now.getHours(), now.getMinutes() + 1);
  return DifferenceInDays(christmas, now);
}

function daysLeft(message) {
  var now = new Date();
  var days = daysUntilChristmas(now);
  var content = days !== 0 ? "ONLY " + days + " " + pluralize("DAY", days) + " UNTIL CHRISTMAS!!" : "🎄☃️☃️🎄🎁 " + "!!TODAY IS CHRISTMAS!!" + " 🎁🎄☃️☃️🎄";
  var remaining = {
    content: content
  };
  message.channel.send(remaining);
  
}

exports.festivize = festivize;
exports.pluralize = pluralize;
exports.daysUntilChristmas = daysUntilChristmas;
exports.daysLeft = daysLeft;
/* date-fns/differenceInDays Not a pure module */
