// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Js_null_undefined = require("rescript/lib/js/js_null_undefined.js");

function send(channel, text) {
  return channel.send({
              content: text
            });
}

function sendEmbed(channel, embed) {
  return channel.send({
              embeds: [embed]
            });
}

function embed(color, title, description, footer, param) {
  return {
          color: Js_null_undefined.fromOption(color),
          title: Js_null_undefined.fromOption(title),
          description: Js_null_undefined.fromOption(description),
          footer: Js_null_undefined.fromOption(Belt_Option.map(footer, (function (f) {
                      return {
                              text: f
                            };
                    })))
        };
}

exports.send = send;
exports.sendEmbed = sendEmbed;
exports.embed = embed;
/* No side effect */
