// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Builders = require("@discordjs/builders");

var Message = {};

var Channel = {};

function footer(text) {
  return {
          text: text
        };
}

function field(name, value, inline) {
  return {
          name: name,
          value: value,
          inline: inline
        };
}

var Embed = {
  footer: footer,
  field: field
};

var Interaction = {};

function make(name, description) {
  return new Builders.SlashCommandBuilder().setName(name).setDescription(description);
}

function config(command, interaction) {
  return {
          command: command,
          interaction: interaction
        };
}

var Command = {
  make: make,
  config: config
};

exports.Message = Message;
exports.Channel = Channel;
exports.Embed = Embed;
exports.Interaction = Interaction;
exports.Command = Command;
/* @discordjs/builders Not a pure module */
