// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Env = require("./Env.bs.js");

var shitpost = Env.getExn("CHANNEL_SHITPOST");

var Channels = {
  shitpost: shitpost
};

exports.Channels = Channels;
/* shitpost Not a pure module */
