// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var StdLib = require("./StdLib.bs.js");
var Builders = require("@discordjs/builders");

function define(command, interaction) {
  return {
          command: command,
          interaction: interaction
        };
}

function make(name, description, subcommandsOpt, param) {
  var subcommands = subcommandsOpt !== undefined ? subcommandsOpt : [];
  var command = new Builders.SlashCommandBuilder().setName(name).setDescription(description);
  Curry._2(StdLib.A.forEach, subcommands, (function (builder) {
          command.addSubcommand(builder);
          
        }));
  return command;
}

function subcommand(name, description, optionsOpt, param, subcmd) {
  var options = optionsOpt !== undefined ? optionsOpt : [];
  subcmd.setName(name).setDescription(description);
  Curry._2(StdLib.A.forEach, options, (function (builder) {
          subcmd.addStringOption(builder);
          
        }));
  return subcmd;
}

function stringOption(name, description, requiredOpt, param, option) {
  var required = requiredOpt !== undefined ? requiredOpt : false;
  return option.setName(name).setDescription(description).setRequired(required);
}

exports.define = define;
exports.make = make;
exports.subcommand = subcommand;
exports.stringOption = stringOption;
/* StdLib Not a pure module */
