// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_MapInt = require("rescript/lib/js/belt_MapInt.js");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

function normalizeByInt(arr, by) {
  return Belt_Array.reduce(arr, undefined, (function (m, v) {
                return Belt_MapInt.set(m, Curry._1(by, v), v);
              }));
}

function normalizeByString(arr, by) {
  return Belt_Array.reduce(arr, undefined, (function (m, v) {
                return Belt_MapString.set(m, Curry._1(by, v), v);
              }));
}

function uniq(arr) {
  var values = {};
  Belt_Array.forEach(arr, (function (item) {
          values[item] = true;
          
        }));
  return Object.keys(values);
}

function joinList(l, joinWith) {
  return Belt_List.toArray(l).join(joinWith);
}

exports.normalizeByInt = normalizeByInt;
exports.normalizeByString = normalizeByString;
exports.uniq = uniq;
exports.joinList = joinList;
/* No side effect */
