/** @from /api/v3/activities/{id} */
export const activity_indoor_with_heartrate = <const>{
  "resource_state": 3,
  "athlete": {
    "id": 6913382,
    "resource_state": 1
  },
  "name": "Trunk II",
  "distance": 0.0,
  "moving_time": 3429,
  "elapsed_time": 3429,
  "total_elevation_gain": 0,
  "type": "Crossfit",
  "id": 4768492508,
  "external_id": "garmin_push_6253278374",
  "upload_id": 5089018783,
  "start_date": "2021-02-11T02:20:12Z",
  "start_date_local": "2021-02-10T18:20:12Z",
  "timezone": "(GMT-08:00) America/Los_Angeles",
  "utc_offset": -28800.0,
  "start_latlng": null,
  "end_latlng": null,
  "location_city": null,
  "location_state": null,
  "location_country": "United States",
  "start_latitude": null,
  "start_longitude": null,
  "achievement_count": 0,
  "kudos_count": 1,
  "comment_count": 0,
  "athlete_count": 1,
  "photo_count": 0,
  "map": {
    "id": "a4768492508",
    "polyline": "",
    "resource_state": 3
  },
  "trainer": true,
  "commute": false,
  "manual": false,
  "private": false,
  "visibility": "everyone",
  "flagged": false,
  "gear_id": null,
  "from_accepted_tag": false,
  "upload_id_str": "5089018783",
  "average_speed": 0.0,
  "max_speed": 0.0,
  "average_temp": 27,
  "has_heartrate": true,
  "average_heartrate": 122.2,
  "max_heartrate": 164.0,
  "heartrate_opt_out": false,
  "display_hide_heartrate_option": true,
  "elev_high": 32.0,
  "elev_low": 32.0,
  "pr_count": 0,
  "total_photo_count": 0,
  "has_kudoed": false,
  "suffer_score": 10.0,
  "description": "ay my leg works",
  "calories": 522.0,
  "perceived_exertion": null,
  "prefer_perceived_exertion": false,
  "device_name": "Garmin fēnix 6S Pro",
  "embed_token": "270a00f65adcfe43ca943c1f219f8c2b7cd586b2",
  "available_zones": [
    "heartrate"
  ]
};

/** @from /api/v3/activities/{id} */
export const activity_outdoor_with_heartrate = <const>{
  "resource_state": 3,
  "athlete": {
    "id": 6913382,
    "resource_state": 1
  },
  "name": "Almaden Quicksilver Trail Run",
  "distance": 8680.9,
  "moving_time": 4017,
  "elapsed_time": 4084,
  "total_elevation_gain": 290.0,
  "type": "Run",
  "workout_type": 0,
  "id": 4713981195,
  "external_id": "garmin_push_6199423470",
  "upload_id": 5032465431,
  "start_date": "2021-01-31T19:47:47Z",
  "start_date_local": "2021-01-31T11:47:47Z",
  "timezone": "(GMT-08:00) America/Los_Angeles",
  "utc_offset": -28800.0,
  "start_latlng": [
    37.2,
    -121.86
  ],
  "end_latlng": [
    37.2,
    -121.86
  ],
  "location_city": null,
  "location_state": null,
  "location_country": "United States",
  "start_latitude": 37.2,
  "start_longitude": -121.86,
  "achievement_count": 0,
  "kudos_count": 1,
  "comment_count": 0,
  "athlete_count": 1,
  "photo_count": 0,
  "trainer": false,
  "commute": false,
  "manual": false,
  "private": false,
  "visibility": "everyone",
  "flagged": false,
  "gear_id": null,
  "from_accepted_tag": false,
  "upload_id_str": "5032465431",
  "average_speed": 2.161,
  "max_speed": 3.4,
  "average_cadence": 68.5,
  "average_temp": 24,
  "has_heartrate": true,
  "average_heartrate": 151.8,
  "max_heartrate": 168.0,
  "heartrate_opt_out": false,
  "display_hide_heartrate_option": true,
  "elev_high": 312.8,
  "elev_low": 132.2,
  "pr_count": 0,
  "total_photo_count": 0,
  "has_kudoed": false,
  "suffer_score": 26.0,
  "description": "New Almaden - Randol trail loop",
  "calories": 923.0,
  "perceived_exertion": null,
  "prefer_perceived_exertion": false,
  "photos": {
    "primary": null,
    "count": 0
  },
  "device_name": "Garmin fēnix 6S Pro",
  "embed_token": "f46384d99cd72bfdc6686f8aaf99fce561299b3f",
  "available_zones": [
    "heartrate",
    "pace"
  ]
};

/** @from /api/v3/activities/{id} */
export const activity_outdoor_no_heartrate = <const>{
  "resource_state": 3,
  "athlete": {
    "id": 6913382,
    "resource_state": 1
  },
  "name": "Afternoon Run",
  "distance": 2630.6,
  "moving_time": 1061,
  "elapsed_time": 1111,
  "total_elevation_gain": 0.0,
  "type": "Run",
  "workout_type": 0,
  "id": 860020260,
  "external_id": "3d9eb2414beeb40bff6b8ec3f329e11d",
  "upload_id": 951932045,
  "start_date": "2017-02-09T00:13:17Z",
  "start_date_local": "2017-02-08T16:13:17Z",
  "timezone": "(GMT-08:00) America/Los_Angeles",
  "utc_offset": -28800.0,
  "start_latlng": [
    37.31,
    -121.9
  ],
  "end_latlng": [
    37.31,
    -121.9
  ],
  "location_city": null,
  "location_state": null,
  "location_country": "United States",
  "start_latitude": 37.31,
  "start_longitude": -121.9,
  "achievement_count": 1,
  "kudos_count": 1,
  "comment_count": 0,
  "athlete_count": 1,
  "photo_count": 0,
  "trainer": false,
  "commute": false,
  "manual": false,
  "private": false,
  "visibility": "everyone",
  "flagged": false,
  "gear_id": null,
  "from_accepted_tag": false,
  "upload_id_str": "951932045",
  "average_speed": 2.479,
  "max_speed": 4.1,
  "has_heartrate": false,
  "heartrate_opt_out": false,
  "display_hide_heartrate_option": false,
  "elev_high": 44.3,
  "elev_low": 37.1,
  "pr_count": 0,
  "total_photo_count": 0,
  "has_kudoed": false,
  "suffer_score": null,
  "description": null,
  "calories": 312.7,
  "perceived_exertion": null,
  "prefer_perceived_exertion": null,
  "device_name": "Strava Android App",
  "embed_token": "c7261ce0ad846f60a8fed10961a5550d5c25317d",
  "available_zones": [
    "pace"
  ]
};

/** @from /api/v3/activities/{id} */
export const activity_manual_run = <const>{
  "resource_state": 3,
  "athlete": {
    "id": 6913382,
    "resource_state": 1
  },
  "name": "Manual Activity",
  "distance": 8046.7,
  "moving_time": 3600,
  "elapsed_time": 3600,
  "total_elevation_gain": 0.0,
  "type": "Run",
  "workout_type": null,
  "id": 4772307755,
  "external_id": null,
  "upload_id": null,
  "start_date": "2021-02-11T19:20:00Z",
  "start_date_local": "2021-02-11T11:20:00Z",
  "timezone": "(GMT-08:00) America/Los_Angeles",
  "utc_offset": -28800.0,
  "start_latlng": null,
  "end_latlng": null,
  "location_city": null,
  "location_state": null,
  "location_country": "United States",
  "start_latitude": null,
  "start_longitude": null,
  "achievement_count": 0,
  "kudos_count": 0,
  "comment_count": 0,
  "athlete_count": 1,
  "photo_count": 0,
  "map": {
    "id": "a4772307755",
    "polyline": null,
    "resource_state": 3
  },
  "trainer": false,
  "commute": false,
  "manual": true,
  "private": false,
  "visibility": "everyone",
  "flagged": false,
  "gear_id": null,
  "from_accepted_tag": null,
  "average_speed": 2.235,
  "max_speed": 0.0,
  "has_heartrate": false,
  "heartrate_opt_out": false,
  "display_hide_heartrate_option": false,
  "pr_count": 0,
  "total_photo_count": 0,
  "has_kudoed": false,
  "suffer_score": null,
  "description": "",
  "calories": 887.9,
  "perceived_exertion": null,
  "prefer_perceived_exertion": null,
  "segment_efforts": [],
  "best_efforts": [],
  "photos": {
    "primary": null,
    "count": 0
  },
  "embed_token": "c7509947e6f573741d8317cb9b8c8c038ae90bec",
  "available_zones": [
    "pace"
  ]
};

/** @from /api/v3/activities/{id} */
export const activity_manual_workout = <const>{
  "resource_state": 3,
  "athlete": {
    "id": 6913382,
    "resource_state": 1
  },
  "name": "Manual Workout",
  "distance": 0.0,
  "moving_time": 3600,
  "elapsed_time": 3600,
  "total_elevation_gain": 0.0,
  "type": "Workout",
  "id": 4772310192,
  "external_id": null,
  "upload_id": null,
  "start_date": "2021-02-11T19:20:00Z",
  "start_date_local": "2021-02-11T11:20:00Z",
  "timezone": "(GMT-08:00) America/Los_Angeles",
  "utc_offset": -28800.0,
  "start_latlng": null,
  "end_latlng": null,
  "location_city": null,
  "location_state": null,
  "location_country": "United States",
  "start_latitude": null,
  "start_longitude": null,
  "achievement_count": 0,
  "kudos_count": 0,
  "comment_count": 0,
  "athlete_count": 1,
  "photo_count": 0,
  "map": {
    "id": "a4772310192",
    "polyline": null,
    "resource_state": 3
  },
  "trainer": false,
  "commute": false,
  "manual": true,
  "private": false,
  "visibility": "everyone",
  "flagged": false,
  "gear_id": null,
  "from_accepted_tag": null,
  "average_speed": 0.0,
  "max_speed": 0.0,
  "has_heartrate": false,
  "heartrate_opt_out": false,
  "display_hide_heartrate_option": false,
  "pr_count": 0,
  "total_photo_count": 0,
  "has_kudoed": false,
  "suffer_score": null,
  "description": "",
  "calories": 0,
  "perceived_exertion": null,
  "prefer_perceived_exertion": null,
  "segment_efforts": [],
  "photos": {
    "primary": null,
    "count": 0
  },
  "embed_token": "803bc05c4345ee1ffd7d0d2683ceb80710e30360",
  "available_zones": []
};

/** @from /api/v3/activities/{id}/streams?keys=time,heartrate */
export const blank_stream = [
  {
    "type": "heartrate",
    "data": [],
    "series_type": "time",
    "original_size": 1648,
    "resolution": "high"
  },
  {
    "type": "time",
    "data": [],
    "series_type": "time",
    "original_size": 1648,
    "resolution": "high"
  }
]