// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(label, style, custom_id, disabled, param) {
  return {
          type: 2,
          style: style + 1 | 0,
          label: label,
          custom_id: custom_id,
          disabled: disabled
        };
}

var Button = {
  make: make
};

function make$1(label, custom_id, style, min_length, max_length, required, value, placeholder, param) {
  return {
          type: 4,
          custom_id: custom_id,
          style: style ? 2 : 1,
          label: label,
          min_length: min_length,
          max_length: max_length,
          required: required,
          value: value,
          placeholder: placeholder
        };
}

var TextInput = {
  make: make$1
};

function row(components) {
  return {
          type: 1,
          components: components
        };
}

exports.Button = Button;
exports.TextInput = TextInput;
exports.row = row;
/* No side effect */
