// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Options = {};

var ChatInputCommand = {};

var Button = {};

var ModalSubmit = {};

function details(i) {
  if (i.isCommand()) {
    return {
            TAG: /* ChatInput */0,
            _0: i
          };
  } else if (i.isButton()) {
    return {
            TAG: /* Button */1,
            _0: i
          };
  } else if (i.isModalSubmit()) {
    return {
            TAG: /* ModalSubmit */2,
            _0: i
          };
  } else {
    return /* Unhandled */0;
  }
}

exports.Options = Options;
exports.ChatInputCommand = ChatInputCommand;
exports.Button = Button;
exports.ModalSubmit = ModalSubmit;
exports.details = details;
/* No side effect */
