// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var CommandType = {
  slash: 1
};

var OptionType = {
  sub_command: 1,
  sub_command_group: 2,
  string: 3,
  integer: 4,
  $$boolean: 5,
  user: 6,
  channel: 7,
  role: 8,
  mentionable: 9,
  number: 10,
  attachment: 11
};

var $$Permissions = {
  kick: 2
};

function make(t) {
  return t;
}

exports.CommandType = CommandType;
exports.OptionType = OptionType;
exports.$$Permissions = $$Permissions;
exports.make = make;
/* No side effect */
