// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function find(x) {
  return "foo";
}

function queries(coll) {
  return {
          find: (function (q) {
              return Promise.resolve(undefined);
            }),
          findOne: (function (q) {
              return Promise.resolve(undefined);
            })
        };
}

var workouts = {
  name: "workouts"
};

exports.find = find;
exports.workouts = workouts;
exports.queries = queries;
/* No side effect */
